version: '3'

services:
    todo_frontend:
        image: xaviergrool/self-made:maven-3.6.3-jdk8-ali
        networks:
          - public-net
        volumes:
          - "C:\\Users\\yinzi\\Desktop\\microservice\\todo-frontend:/root/app"
          - "C:\\Users\\yinzi\\Desktop\\.m2:/root/.m2"
        ports:
          - "9002:9002"
        command: mvn -f /root/app spring-boot:run

networks:
    public-net:
      external: true