eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.0.2:8761/eureka/

server:
  port: 9000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true