version: '3'

services:
    confsvr:
        image: my-maven:3.6.3-jdk-8-ali
        networks:
          - public-net
        volumes:
          - "C:\\Users\\yinzi\\Desktop\\microservice\\confsvr:/root/app"
          - "C:\\Users\\yinzi\\Desktop\\.m2:/root/.m2"
        ports:
          - "9003:9003"
        command: mvn -f /root/app spring-boot:run

networks:
    public-net:
      external: true